In [1]:
import numpy as np

# Que 1

In [2]:
ip=np.array([2,1,3,5])

In [3]:
# approach 1
def performVander(v):
    l=[]
    for k in range(len(v)):
        l.append(list(i**(len(v)-k-1) for i in v))
    return l
        

In [4]:
op=np.array(performVander(ip)).T
op

array([[  8,   4,   2,   1],
       [  1,   1,   1,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [5]:
# approach 2
op=np.vander(ip)
op

array([[  8,   4,   2,   1],
       [  1,   1,   1,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

# Que 2

In [7]:
ip=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3

In [23]:
def findMovingAverage(ip,k):
    newip=np.cumsum(ip)
    print(newip);
    op=[]
    if(len(ip)<3):
        return op;
    else:
        op.append(newip[2]/k)
    for i in range(3,len(newip)):
        op.append((newip[i]-newip[i-3])/k)
    return op

In [24]:
np.array(findMovingAverage(ip,k))

[  3   8  15  17  25  35  46 111 183 264 363 463 613]


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])